version: '3'

services:

  nginx:
    image: nginx
    container_name: "laravel-nginx"
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: ./docker/php
    container_name: "laravel-php"
    volumes:
      - ./src:/var/www

  mysql:
    image: mysql:5.7
    container_name: "laravel-mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 13306:3306

  redis:
    image: redis:alpine
    container_name: "laravel-redis"
    ports:
      - 16379:6379